Cargo.toml, src/compile.rs, src/main.rs, src/pycors.rs, src/settings.rs, src/utils.rs
Instead of using a configuration file, dynamically load installed python versions.
=> Settings refactored

src/commands/setup.rs
=> Verify that `~/.bash_profile` contains the line we want to append

src/config.rs
=> Walk up directory hierarchy to find toolchain file

README.md, src/commands/install/compile.rs, src/commands/install/download.rs, src/shim.rs
=> Install some packages (using pip) after new Python install

src/commands/install.rs, src/commands/install/compile.rs
Closes #48, finally closes #41.
=> Allow installing extra packages for already installed toolchains

Cargo.lock, Cargo.toml, src/commands/install/compile.rs
=> Remove '--with-pydebug' flag to configure

Cargo.lock, Cargo.toml, Cross.toml, build.rs, src/main.rs
Harmonize version across Cargo.toml, clap and git tags.
Closes #49.
=> Harmonize version

azure-pipelines.yml
=> Re-enable github releases

src/commands/install.rs, src/commands/list.rs, src/settings.rs, src/utils.rs
=> Prioritize custom installs over system ones

src/commands/install.rs, src/commands/install/compile.rs, src/commands/install/download.rs, src/commands/install/pip.rs, src/commands/install/windows.rs, src/utils.rs
=> Windows support (precompiled)

.gitignore, README.md, azure-pipelines.yml, coverage/tarpaulin.sh, coverage/tarpaulin_upload_codecov_io.sh
Add some code coverage functionality.
=> Code coverage

azure-pipelines.yml
=> Use zip for release archives

src/commands/install/unix.rs
=> Tk fix for OSX

README.md, src/commands.rs, src/commands/setup.rs
=> Replace bash_profile with bashrc

Cargo.lock, docker-compose.yml, src/commands/setup.rs, src/commands/setup/bash.rs, src/utils.rs
Small bug fixes in `setup bash` command.
=> Prepare for v0.2.1

src/cache.rs, src/commands/install/pip.rs, src/commands/install/unix.rs, src/commands/install/windows.rs, src/commands/setup.rs, src/commands/setup/bash.rs, src/download.rs, src/os.rs, src/shim.rs, src/toolchain.rs, src/utils.rs, src/utils/directory.rs
Change how `$PYCORS_HOME` variable is obtained so we can mock it for better tests.
=> Refactored directory module 

Cargo.lock, Cargo.toml, src/cache.rs, src/commands/install.rs, src/commands/install/pip.rs, src/commands/install/unix.rs, src/commands/install/windows.rs, src/commands/setup.rs, src/commands/setup/bash.rs, src/dir_monitor.rs, src/download.rs, src/main.rs, src/os.rs, src/shim.rs, src/toolchain.rs, src/utils.rs, src/utils/directory.rs
This adds more unit tests and refactors some part to make testing easier and reporting better errors to the user.
For now, `utils/directory.rs` and `cache.rs` have been worked on.
=> Add more testing

.github/workflows/ci.yml
=> CI: Bump to macOS Catalina 10.15

src/commands/setup.rs, tests/integration/setup/bash.rs, tests/integration/setup/powershell.rs
Print a help message after running `pycors setup <shell>`.
=> Print nice message after setuping shell

.github/workflows/ci.yml, .github/workflows/nightly.yml, README.md, src/commands/setup.rs
Add CI nightly run for security audit.
=> CI nightly audit

src/toolchain/tests.rs, src/utils/directory.rs, tests/integration/mod.rs
=> Namespace 'cpython' in installed dir

src/commands.rs, src/commands/install.rs, src/commands/setup.rs, src/commands/setup/zsh.rs, src/utils/directory.rs
Adds Zsh support, now the default shell on macOS.
=> Zsh support

docker-compose.yml, docker/alpine/Dockerfile, docker/debian/sid/Dockerfile, docker/fedora/Dockerfile, docker/ubuntu/Dockerfile
Following project rename, docker images had to be adapted.
Also add a debian sid docker image.
=> Fix docker images

Cargo.lock, Cargo.toml, src/commands.rs, src/main.rs, src/toolchain.rs
Implement an optional self-update (enabled by default).
TODO:
Closes #11.
=> Self update

Cargo.lock, Cargo.toml
`self-update` released an update, fork not required anymore.
=> Update self update

.cargo/config, .github/workflows/ci.yml, Cargo.toml, hygeia_test_helpers/Cargo.toml, hygeia_test_helpers/build.rs, hygeia_test_helpers/src/lib.rs
Artifacts are now properly built, using the proper target triple.
=> CI: Fix build targets

Cargo.toml
Replace fork with released version.
=> Get rid of self_update fork; v0.12 released

Cargo.lock
Update lock file for self_update 0.12
=> Update lock file for self_update 0.12
